services:
  - type: web
    name: fact-check-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
